services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy # Wait for health, not just start
      cache_server:
        condition: service_started

  # Your Redis Server
  cache_server:
    image: redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - cache_server

  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_tuto_task
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # This checks if MySQL is actually accepting queries
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
